apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruby-http-server
  name: ruby-http-server
  namespace: ruby-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby-http-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ruby-http-server
    spec:
      containers:
      - image: rubyserver:latest
        imagePullPolicy: IfNotPresent
        name: ruby-http-server
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ruby-http-server-svc
  namespace: ruby-webserver
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: ruby-http-server
    
