apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{app.name}}
  name: {{app.name}}
  namespace: {{name_space}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{app.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{app.name}}
    spec:
      containers:
      - image: {{ image_name }}:latest
        imagePullPolicy: IfNotPresent
        name: {{app.name}}
        ports:
        - containerPort: {{app.port}}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: {{app.port}}
          initialDelaySeconds: 90
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{app.name}}-svc
  namespace: {{name_space}}
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: {{app.name}}

